name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'

      - name: Install curl
        run: |
          apt-get update
          apt-get install -y curl
      - name: Set up Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
      - name: Set up Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip

      - name: Set up Git Safe Directory
        run: |
          git config --global --add safe.directory MLops-CI/.github/workflows/
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          #installation of the requirements
          pip3 install -r requirements.txt
          #run the model 
          python3 model.py
          #define new readme file and define the machine learning pipeline
          echo "##Model Metrics" > report.md
          #inside the reamfile we will write the information from the text file  
          cat metrics.txt >> report.md
          #make it accessible for team members
          cml-send-comment report.md
    
